"""Campos adicionales eliminados por la complejidad de cambiarlos

Revision ID: 39d7218706e6
Revises: b0a9f596a99e
Create Date: 2024-12-10 19:11:46.706189

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39d7218706e6'
down_revision = 'b0a9f596a99e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Reporte', schema=None) as batch_op:
        batch_op.drop_column('nivel_severidad')
        batch_op.drop_column('hora_reporte')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Reporte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hora_reporte', postgresql.TIME(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nivel_severidad', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
