"""Cambiar texto_reporte a tipo TEXT

Revision ID: afb7a24f1027
Revises: e9e53fae00a7
Create Date: 2024-10-27 17:46:28.269744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afb7a24f1027'
down_revision = 'e9e53fae00a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Reporte', schema=None) as batch_op:
        batch_op.alter_column('texto_reporte',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Reporte', schema=None) as batch_op:
        batch_op.alter_column('texto_reporte',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
