"""Added student key to Reports

Revision ID: e9e53fae00a7
Revises: 
Create Date: 2024-10-27 13:47:48.077453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9e53fae00a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Reporte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_estudiante', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'Estudiante', ['id_estudiante'], ['boleta'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Reporte', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_estudiante')

    # ### end Alembic commands ###
